notifications:
  email: false

language: cpp

os:
  - linux
  - osx

compiler:
  - gcc
  - clang

addons:
  apt:
    sources:
      - george-edison55-precise-backports # cmake 3.2.3
    packages:
      - cmake
      - cmake-data
      - valgrind
      - lcov

install:
  - sudo pip install gcovr

script:
  - mkdir -p test/build
  - cd test/build
  - cmake -DBUILDNAME=Linux-$CXX ..
  - make NightlyStart
  - make NightlyTest
  - make NightlySubmit
