site_name: CTest Extension module
site_author: Vlad Vinogradov

repo_url: https://github.com/jet47/ctest-ext

pages:
- ['index.md', 'Home']
- ['usage/intro.md', 'Usage', 'Introduction']
- ['usage/project_script.md', 'Usage', 'Create project testing script']
- ['usage/run_test.md', 'Usage', 'Run project testing script']
- ['usage/commands.md', 'Usage', 'CTest Ext Commands']
- ['options/mandatory.md', 'Options', 'Mandatory testing options']
- ['options/repository.md', 'Options', 'Repository settings']
- ['options/testing.md', 'Options', 'Optional testing settings']
- ['ci/common.md', 'CI', 'Usage with CI systems']
- ['ci/travis.md', 'CI', 'Travis CI example']
- ['ci/jenkins.md', 'CI', 'Jenkins CI example']
- ['about/license.md', 'About', 'License']

copyright: Copyright &copy; 2014-2016, Vlad Vinogradov.
