site_name: CTest Extension module
site_author: Vlad Vinogradov

repo_url: https://github.com/jet47/ctest-ext

pages:
- ['index.md', 'Home']
- ['usage/quick_start.md', 'Usage', 'Quick start']
- ['usage/configuration.md', 'Usage', 'Configuration']
- ['usage/example.md', 'Usage', 'Example of project script']
- ['options/mandatory.md', 'Options', 'Mandatory testing options']
- ['options/repository.md', 'Options', 'Repository settings']
- ['options/testing.md', 'Options', 'Optional testing settings']
- ['ci/common.md', 'CI', 'Usage with CI systems']
- ['ci/travis.md', 'CI', 'Travis CI example']
- ['ci/jenkins.md', 'CI', 'Jenkins CI example']
- ['about/license.md', 'About', 'License']

copyright: Copyright &copy; 2014, Vlad Vinogradov.
